### ISSUE TITLE
Move wallet addresses away from Peercoin format

### ISSUE THREAD

**Issue by mitchellcash** [PaycoinFoundation/paycoin#107]
As discussed in issue #71 we should investigate how we can move our address generation away from the format used by Peercoin.

We need to ensure that while doing this we retain backwards compatibility with Peercoin style addresses on the Paycoin network but new addresses are generated in a Paycoin unique format.

**Comment by tvl83** [comment]
What would the purpose of changing the format so that it isn't the same as the peercoin format. It does not hurt anything.

**Comment by mitchellcash** [comment]
It's common among cryptocurrencies to have their own unique format and I think we still need continue to forge our own path and this is just one of many steps.

Helps us differentiate from the pack and removes the thought it puts in peoples mind, subliminal or otherwise, "this is just like Peercoin, why don't I just use Peercoin?". We want to continue and expand our user base and this might help.

**Comment by MitchellMint** [comment]
I vote decimal 76

**Comment by mitchellcash** [comment]
"L"?
Any reasons? Not that there needs to be one per se but if there is all the better :)

**Comment by MitchellMint** [comment]
Could have swore it was X.  http://cryptolife.net/upwg/

**Comment by mitchellcash** [comment]
My mistake yes it's an X, Dash uses this so we need to take that into consideration.

**Comment by MitchellMint** [comment]
E or Y?

**Comment by mitchellcash** [comment]
This bugged me for the longest time but having more time to think about it and seeing different things happen I am happy to leave this as `P`.

Seeing as this generated only small conversation without much resolution I think we should close this.

**Comment by ligerzero459** [comment]
I agree. `P` really does make sense. I'm all for leaving the current address format and closing this
