### ISSUE TITLE
Wallet Synchornizing

### ISSUE THREAD

**Issue by Batminer** [PaycoinFoundation/paycoin#108]
How does one get their wallet to sycn? I have been stuck at 50490 for days. weeks. I have backed up and removed all trace of the app and reinstalled more than once. I am on v0.3.0.0 ( https://github.com/PaycoinFoundation/paycoin/releases ).

**Comment by mitchellcash** [comment]
Hmm mine is working fine. Maybe visit https://talk.paycoin.com and post a topic.

Some of the team there would be happy to help!

**Comment by IngCr3at1on** [comment]
Shutdown the wallet and  try deleting everything from the data directory again except your wallet.dat and paycoin.conf files (always have a backup of your wallet.dat or the private keys it contains).

Before turning the wallet back on go the network list on chainz (https://chainz.cryptoid.info/xpy/#!network) and click either or both of the top two node list options and copy everything it shows into your paycoin.conf (if the paycoin.conf doesn't exist create it and add those addnode lists).

Restart the wallet and wait for it to sync, there's no chance you'll connect to every node in that list cause most will be outbound connections only but you'll at least get a few and that guarantees a connection to good nodes (the seed nodes are supposed to resolve this but that doesn't seem to always be the case).

**Comment by Batminer** [comment]
Thank you. I was able to get this fixed.

**Comment by mitchellcash** [comment]
Good to hear @Batminer :)
Please close.
