### ISSUE TITLE
Paycoin 0.3.1.0 missing binary/installer downloads

### ISSUE THREAD

**Issue by CodeChief** [PaycoinFoundation/paycoin#180]
It's just source, where are the binaries?

**Comment by HyperCommNet** [comment]
They are being generated today and will be release with the Press Release

**Comment by CodeChief** [comment]
Ok thanks.

**Comment by mitchellcash** [comment]
@CodeChief this is now complete, please see: https://github.com/PaycoinFoundation/paycoin/releases/tag/v0.3.1.0

**Comment by mitchellcash** [comment]
Issue resolved, please close.
