### ISSUE TITLE
Unable to start new wallet

### ISSUE THREAD

**Issue by NormB** [PaycoinFoundation/paycoin#181]
Mac 10.10.5 wallet unable to start

Process:               Paycoin [551]
Path:                  /Users/USER/*/Paycoin.app/Contents/MacOS/Paycoin
Identifier:            com.yourcompany.Paycoin
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Paycoin [551]
User ID:               501

Date/Time:             2015-08-30 22:52:30.679 -0400
OS Version:            Mac OS X 10.10.5 (14F27)
Report Version:        11
Anonymous UUID:        B23AC947-697E-4211-E65A-E9B7CF793582

Time Awake Since Boot: 1800 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/lib/libqrencode.3.dylib
  Referenced from: /Users/USER/*/Paycoin.app/Contents/MacOS/Paycoin
  Reason: image not found

Binary Images:
    0x7fff61d30000 -     0x7fff61d66887  dyld (353.2.3) <B1B370A5-479F-3533-8AD7-97B687D4F989> /usr/lib/dyld

Model: MacBookPro11,3, BootROM MBP112.0138.B15, 4 processors, Intel Core i7, 2.8 GHz, 16 GB, SMC 2.19f12
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Graphics: NVIDIA GeForce GT 750M, NVIDIA GeForce GT 750M, PCIe, 2048 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.6f3 16238, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Network Service: iPhone, Ethernet, en4
Serial ATA Device: APPLE SSD SM1024F, 1 TB
USB Device: Internal Memory Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: iPhone
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

**Comment by HyperCommNet** [comment]
Interesting @evanlucas Can you look at this?

**Comment by NormB** [comment]
Looks like this library or something very close to it needs to be statically linked instead of dynamically linked.

https://github.com/robotconscience/ofxQRCodeGenerator <https://github.com/robotconscience/ofxQRCodeGenerator>

Regards,
Norm

**Comment by HyperCommNet** [comment]
I have it running on Yosemite 10.10.3 So lets figure it out.

**Comment by evanlucas** [comment]
Yea. @NormB is correct. libqrencode needs to be statically linked into the binary.

**Comment by HyperCommNet** [comment]
@evanlucas Can this be done in the builder script or does it need to be done in the core code?

**Comment by NormB** [comment]
Generally, this kind of thing (statically vs. dynamically linked libraries) is performed during the “compilation/linking” process which is not associated with any “code” per se.  I don’t know the processes used to compile/link the wallet so it’s hard to offer any more constructive assistance.

The following lines pretty clearly show the error.  Fixing it, well, that’s most likely  a problem for the folks responsible for building the .dmg

Dyld Error Message:
Library not loaded: /usr/local/lib/libqrencode.3.dylib
Referenced from: /Users/USER/*/Paycoin.app/Contents/MacOS/Paycoin
Reason: image not found

Regards,
Norm

**Comment by mitchellcash** [comment]
Agree with @NormB as well. This would be something that needs to be fixed at the build stage not the core code.

How did the other builds get through okay we haven't really changed anything that would make this any different to other builds regarding libqrencode?

**Comment by mitchellcash** [comment]
Actually without knowing the full process you go through I could be mistaken

**Comment by HyperCommNet** [comment]
I don't know @evanlucas made the builder so maybe he can figure it out and send me the patch to fix it

**Comment by mitchellcash** [comment]
I know you are already trying to fix this but also letting you know I am experiencing the same issue on:
`OS Version:            Mac OS X 10.10.5 (14F27)`

I'm guessing the reason you can get it running on your OS X is that it was the build machine as well?

**Comment by chrismcband** [comment]
I had the same error starting the new wallet, also on Mac 10.10.5. I installed qrencode with `brew install qrencode` but now get another problem starting up:
```
Dyld Error Message:
  Library not loaded: /usr/local/lib/libminiupnpc.13.dylib
  Referenced from: /Applications/Paycoin.app/Contents/MacOS/Paycoin
  Reason: image not found
```
There may be a few of these, so looks like it is as suggested a static/dynamic library issue at compile time.

**Comment by mitchellcash** [comment]
Yeah looks like a few of the deps are not being statically linked

**Comment by HyperCommNet** [comment]
Hopefully @evanlucas can fix this as he is the mac master.

**Comment by evanlucas** [comment]
@chrismcband looks like miniupnpc is also not being linked statically. As a temporary workaround, you could `brew install miniupnpc`

**Comment by evanlucas** [comment]
oh wait, this is the qt wallet...

Can yall try running the following and paste the output here:

```
$ otool -L <path to paycoin.app>/Contents/MacOS/Paycoin
```

**Comment by NormB** [comment]
otool -L ./Paycoin
./Paycoin:
	/usr/local/lib/libqrencode.3.dylib (compatibility version 8.0.0, current version 8.4.0)
	/usr/local/lib/libminiupnpc.13.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1153.20.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 48.0.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1347.57.0)
	/usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/local/opt/berkeley-db4/lib/libdb_cxx-4.8.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libboost_filesystem-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libboost_program_options-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libboost_thread-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/QtGui.framework/Versions/4/QtGui (compatibility version 4.8.0, current version 4.8.7)
	/usr/local/lib/QtCore.framework/Versions/4/QtCore (compatibility version 4.8.0, current version 4.8.7)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1153.18.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 62.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)

**Comment by evanlucas** [comment]
@NormB did you compile this yourself?

**Comment by NormB** [comment]
Nope, downloaded it yesterday.

./Paycoin
dyld: Library not loaded: /usr/local/lib/libqrencode.3.dylib
  Referenced from: /Users/gator/Applications/Paycoin.app/Contents/MacOS/./Paycoin
  Reason: image not found
Trace/BPT trap: 5

**Comment by evanlucas** [comment]
Yea, this release binary is borked

**Comment by evanlucas** [comment]
What release version did you download?

**Comment by NormB** [comment]
https://github.com/PaycoinFoundation/paycoin/releases <https://github.com/PaycoinFoundation/paycoin/releases>

osx version has been pulled :)

**Comment by evanlucas** [comment]
Ah ok, that makes more sense....I kept trying to find it

**Comment by NormB** [comment]
I’ve loaded the BROKEN code to:

https://github.com/NormB/pc <https://github.com/NormB/pc>

Note that because it’s broken, I’ll delete the repo it after you have had a chance to copy.

Norm

**Comment by chrismcband** [comment]
Here's my output from otool -L:
```
otool -L /Applications/Paycoin.app/Contents/MacOS/Paycoin
/Applications/Paycoin.app/Contents/MacOS/Paycoin:
	/usr/local/lib/libqrencode.3.dylib (compatibility version 8.0.0, current version 8.4.0)
	/usr/local/lib/libminiupnpc.13.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1153.20.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 48.0.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1347.57.0)
	/usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/local/opt/berkeley-db4/lib/libdb_cxx-4.8.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libboost_filesystem-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libboost_program_options-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libboost_thread-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/QtGui.framework/Versions/4/QtGui (compatibility version 4.8.0, current version 4.8.7)
	/usr/local/lib/QtCore.framework/Versions/4/QtCore (compatibility version 4.8.0, current version 4.8.7)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1153.18.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 62.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by mitchellcash** [comment]
Sorry I forgot to post but mine is identical to @chrismcband

**Comment by esipas** [comment]
has this been fixed yet?

**Comment by mitchellcash** [comment]
@esipas I don't think so. Hopefully soon :)

**Comment by evanlucas** [comment]
I just uploaded a release for OS X for the latest version. Mind trying that?

**Comment by mitchellcash** [comment]
@evanlucas Thanks for that, it's working again :)

**Comment by NormB** [comment]
Just got off the lake. Will try the new build later this evening

**Comment by chrismcband** [comment]
Working for me too, thanks.

**Comment by NormB** [comment]
v0.3.0.2 starts on on the Mac 10.10.5

Blockchain syned ok.  Tested some functionality and it seems to be ok.

**Comment by IngCr3at1on** [comment]
@NormB why are you using 0.3.0.2?

**Comment by NormB** [comment]
Updated version in previous response.
