### ISSUE TITLE
debug.log opens twice

### ISSUE THREAD

**Issue by beulemann** [PaycoinFoundation/paycoin#195]
if click on the debug.log button, the file opens twice.

windows x64
v 0.3.1.0

**Comment by mitchellcash** [comment]
Yeah sorry that was my fault, the fix is in #186. This can be closed

**Comment by mitchellcash** [comment]
This fix is now merged into master as per the above pull request.

**Comment by IngCr3at1on** [comment]
Fix merged into release 0.3.1.1, closing.
