### ISSUE TITLE
linux - version still showing as 3.0.2

### ISSUE THREAD

**Issue by gentamicin** [PaycoinFoundation/paycoin#196]
hi guys, have used the compiled and binary of 3.1.0 , the version number still shows 3.0.2 for me. anybody else with the same issue ?

**Comment by Bige086** [comment]
I was having the same issue when I would "update" to the new wallet builds.  So I deleted the compiled wallet directory with rm: -r -f paycoin , and start with a fresh build.

**Comment by IngCr3at1on** [comment]
@Bige086 you can also fetch any new tags with `git fetch origin`. @gentamicin was saying this was a release build when we spoke though which concerns me as that tag should have been checked by gitian.

**Comment by IngCr3at1on** [comment]
@gentamicin I just downloaded a release build (linux64) and checked the version, it's showing 0.3.1.0 for me.

**Comment by IngCr3at1on** [comment]
Confirmed this was fixed with @gentamicin on Slack (conflicting binaries in user path).

Closing Issue
