### ISSUE TITLE
Windows error: blkindex.dat

### ISSUE THREAD

**Issue by dreddtemptz** [PaycoinFoundation/paycoin#199]
I dont know whats happening, everytime I tried to open the Paycoin Gui it prompt Error blkindex.dat
Please help.

**Comment by IngCr3at1on** [comment]
Most likely the blkindex.dat is corrupt or for a different Berkeley DB version.

If you've been running release builds only those are all built with Berkeley 4.8 for compatibility reasons. However if you compiled a wallet yourself at some point it could be BDB 5 or similar.

I doubt it's the DB version though just stating a possibility. More likely the file was corrupted on a bad shutdown. Just open the paycoin data directory (paths below) and delete everything except the wallat.dat (DO NOT DELETE THE wallet.dat, it has your coins (if you don't have a backup of it or your private keys I would suggest backing it up to a secure place at this time as well)). After you've deleted everything in the data directory (except the wallet.dat of course) restart the wallet and see if it opens properly. Assuming it does just wait for the blockchain to sync.

defaults:
Linux : `~/.paycoin/`
Windows : `%appdata%\Paycoin`
Mac : `~/Library/Application Support/Paycoin`

Ignore your balance until the blockchain is fully synced, if after it's caught up and your balance is incorrect go to `Help` then `Debug Window` and click `Console` type in `repairwallet` and hit enter. It should correct your balance and you should be good to go after that.

**Comment by dreddtemptz** [comment]
It work! Thank you so much.

**Comment by IngCr3at1on** [comment]
No worries man, I'm closing this issue since it's working for you. Have a good one.
