### ISSUE TITLE
Fix v0.3.1.1 release title

### ISSUE THREAD

**Issue by mitchellcash** [PaycoinFoundation/paycoin#224]
Can we fix the title to just be `v0.3.1.1` rather than `v0.3.1.1: Paycoin version 0.3.1.1 is now available from:`

**Comment by IngCr3at1on** [comment]
Just looked, it would appear the release title was automatically appended after the tag; apparently default behavior is to grab the first line from the markdown if the release title is blank.

Since the release notes are a copy of the ones found in /doc this is expected really.

**Comment by mitchellcash** [comment]
Yeah figured it was just something like that. Just seeing if it can be updated to clean it up

**Comment by PaycoinMaster** [comment]
Fixed
