### ISSUE TITLE
Keyboard shortcuts on Receive Coins not working

### ISSUE THREAD

**Issue by IngCr3at1on** [PaycoinFoundation/paycoin#249]
Looks like the only one that works is Copy Address <ctrl+c>
<ctrl+q> for Show QR Code quits the application

None of the others seem to work.

**Comment by IngCr3at1on** [comment]
I've only tested this on linux so let me know if they work on anything else please.

**Comment by IngCr3at1on** [comment]
It would appear that none of the keyboard shortcuts defined by use of Ampersand in the ui file actually have any keyboard shortcuts set to them.

Basically whomever set them was just being silly as they're non-existent. The only one that is is the Ctrl+Q function which is set to quit so this cannot be used for the QR code stuff.

(we also have Alt+1-6 to change tabs.

**Comment by mitchellcash** [comment]
It works for me on Windows. Although from testing I have discovered the Ctrl+S shortcut for Sign Message clashes with the Settings shortcut in the top toolbar.

**Comment by mitchellcash** [comment]
Have you been testing this on your arch box or Ubuntu? I know we ran into this issue on your arch box once before but Ubuntu was fine.

**Comment by IngCr3at1on** [comment]
Specific to my machine config, closing issue.
