### ISSUE TITLE
Headless paycoind stops on certain blocks

### ISSUE THREAD

**Issue by infernobass7** [PaycoinFoundation/paycoin#28]
I have a headless paycoin running on a server but it seems everytime it hits a block ending in 97 it stops and requires the process to be killed and restarted. I heard another person who had it every time it hit a block ending with 50.

**Comment by infernobass7** [comment]
Looking at it again it is every 500 blocks for me. Stops on 397 and 897.

**Comment by IngCr3at1on** [comment]
I've seen issues both in the QT and daemon wallets when syncing the initial blockchain it will sometimes stal briefly but in every case if I leave it sitting it catches up...

Just to make sure I'm understanding the issue... Are you referring specifically to blocks 397 and 897 or are those just the last 3 digits of a higher block number. Basically what I'm trying to figure out is if this is an issue you are only seeing when syncing the initial blockchain or if this is something that happens on a synced daemon running over an extended period of time.

**Comment by paycoindev** [comment]
Just wait.... or restart the client to kickstart the syncing again.

**Comment by IngCr3at1on** [comment]
I've tested this repeatedly on both qt and daemon wallets.

It does pause or stal for a bit every 500 blocks but this starts moving again in less than a minute in most cases. This is likely related to socket implementations and not a concern.

**Comment by IngCr3at1on** [comment]
Other people are reporting this as being more of an issue so I'm re-opening this.

**Comment by coldcycle** [comment]
I have seen this with a mac qt wallet, but not with a headless linux paycoind.

**Comment by coldcycle** [comment]
After the initial download of the blockchain and the blockchain being up-to-date, I don't see any problems with downloading the blockchain on the mac qt wallet.

**Comment by HyperCommNet** [comment]
The issue is looking like line 2293 on the src/main.cpp We have a dev testing a few different fixes. More Info as we progress

**Comment by minercraig** [comment]
I have been running a headless paycoind on ubuntu 14.10 build from source with standard packages and a db-4.8.30 from source without any problems.

**Comment by IngCr3at1on** [comment]
It's weird @minercraig I personally have not been able to replicate the issue on 2 machines and 3 VMs... (Arch, Ubuntu 12.04, 14.04 and Debian. All with different db versions.

Deleted and re-synced blockchains a few dozen times when I was looking into it.

**Comment by hlooman** [comment]
I can replicate the problem on dedicated servers running Centos, compiled from source, also on a VM box running Ubuntu 14.04 with standard packages. First stall at block 8045, then pretty much every 500 blocks at xx045 and xx545 until over 18545 after which it always runs up to sync the rest without any stalls.

**Comment by minercraig** [comment]
It might be a coincidence but there is a checkpoint at 8047. The checkpoints don't follow the rules for being good checkpoints either.

**Comment by hlooman** [comment]
The stall of download of the blockchain is imho caused by main.cpp line 2292 IsInitialBlockDownload() not being evaluated properly, which leads back to issues in checkpoints.cpp all pointing back to the original issues with checkpoints not functioning.
The fix is taking out the return false on line 2294 in main.cpp, this makes the blockchain download completely in all cases I tested, but I want others' opinion on possible side effects of taking out this line.

**Comment by HyperCommNet** [comment]
@hlooman If you want to make a pull request so we can get the community to go over the concept and do testing and see if they all agree.

**Comment by IngCr3at1on** [comment]
I was finally able to replicate this on a remote (ubuntu) server with paycoind compiled from master.

I tried recompiling with the return false commented out (little curious why I haven't been able to replicate this on any of my own systems), it does stall for a moment but it then proceeds to move on where-as the non-modified daemon on the same machine does not progress without restart.

I'm not sure about possible negative impacts but it would appear this works for getting sync to progress.

**Comment by AleCrypto** [comment]
Quite nasty here, this bug isn't solved yet. No professionalism or community help there.

**Comment by IngCr3at1on** [comment]
I assure you @AleCrypto this bug is at the top of the list for things to solve (I know more than myself are working on it).

**Comment by xslugx** [comment]
So the error is happening because it is looking for proof of stake, however proof of stake did not start until later in the project. Is there a way to only have it check for proof of stake AFTER the first 18500 blocks are downloaded?

**Comment by xslugx** [comment]
https://bitcointalk.org/index.php?topic=819896.0 this is in regards to the checkpoints. I would say at this point it would be safe to remove the line of code based off of the information in this post. Being able to download the block chain and fix the qtwallet will certainly keep people using paycoin, at the moment it seems almost impossible to load the wallet and get it functioning again without multiple restarts good work guys!

**Comment by mitchellcash** [comment]
I would recommend reading this as well. 
https://www.peercointalk.org/index.php?topic=1946.0;wap2

Sheds some more light on why checkpoints are there and why we would leave them in there.

**Comment by xslugx** [comment]
Thanks for that. Just trying to help anyway I can. I'm an new dev I have
worked on 1 or 2 projects and never really finished them but more to learn
about the technology it self. I will read the article when I get home, and
I will also keep looking to help resolve the issue. And again thank you for
your hard work!

**Comment by xslugx** [comment]
I see what you are saying now. Peercoin also is staking the thread I was
reading the link I posted was about them removing checkpoints from Bitcoin.
So I can see the differences.

**Comment by IngCr3at1on** [comment]
@PaycoinMaster I believe this is safe to close.
