### ISSUE TITLE
This happened to a dnsseed.

### ISSUE THREAD

**Issue by PaycoinMaster** [PaycoinFoundation/paycoin#292]
************************
EXCEPTION: St9bad_alloc
std::bad_alloc
paycoin in ThreadMessageHandler()

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

**Comment by PaycoinMaster** [comment]
Just happened again on a different Seed

**Comment by IngCr3at1on** [comment]
So it seems the commit I was hoping would fix some of the memory issues didn't help quite as much as I hoped. bad_alloc is related to memory allocation; if you are running DNS seeds on limited memory this is really expected when you consider that connections are handled in memory and dns seeds obviously handle more connections than any other node.

**Comment by PaycoinMaster** [comment]
Ok, then i just need to find my limit on connections on these seeds and set it to under that.

**Comment by IngCr3at1on** [comment]
Unfortunately that sounds about right yes.
