### ISSUE TITLE
Syncing stalled

### ISSUE THREAD

**Issue by RdeWilde** [PaycoinFoundation/paycoin#294]
I had two nodes syncing thru 'connect' to two nodes with blockchain validated against ledger.

Now both nodes are stuck:
http://108.61.103.237/ stuck at 328798 328798 https://ledger.paycoin.com/block/84f73630aafe8f3e371bdbe12a517377092332314aba184155eb4edc6829cffa
http://104.238.187.227/ stuck at 317886 https://ledger.paycoin.com/block/4cfb3104b94cd7bd006203e1a7d99a570c639d2a0877159e5f6756b83f4fd73c

In the debug log there are many askfor block lines and also many of these errors:

```ERROR: CheckProofOfStake() : INFO: read txPrev failed
WARNING: ProcessBlock(): check proof-of-stake failed for block 151eb6b86abbd3cf79b020b6f81e5aa1027092c9cabfd182fadc9faf9ca8b977
received block 25407f5c465bc0c0b45c```

```ERROR: CheckProofOfStake() : INFO: check kernel failed on coinstake a6a95922fe324f4089dac4dbe33e8068e1237a6f36a05d9bd6d3214d406f59fc, hashProof=0000000000000000000000000000000000000000000000000000000000000000
WARNING: ProcessBlock(): check proof-of-stake failed for block 0753fffdd93196cd9aee163d51741884e9002fcca7f9260b3eccd63b5b2b21cb
received block 6b7b91378026b2edd430
ERROR: CheckProofOfStake() : INFO: read txPrev failed```

Also stuff like this (which is normal I think)
askfor block 16649189eb80f9d0d1f7   1445726500000000
askfor block 89f59de7e1ae1225ebe4   1445726500000000
askfor block 15444ef9336bd839fe8a   1445726380000000
askfor block 0c9c2149fa61ceceb5eb   1445726380000000
askfor block f0033f21df779fd97938   1445726380000000
askfor block 2986ffc0855684c8e1c1   1445726260000000
askfor block 482c9d0207d312e3f814   1445725420000000
askfor block e24248e239055d146595   1445725300000000
askfor block cf99d0037473f9fda792   1445725180000000
askfor block a5bcb24e13186363d0a0   1445723500000000
askfor block 6eecf10d2004daf23cfc   1445723500000000
askfor block 5c18f57353d75b1b31a3   1445723500000000
askfor block 9068620338cbeb87ffc6   1445726620000000
askfor block f4696c9652bca4c0f833   1445726260000000
askfor block 01bee4ba24e944ecb268   1445726140000000
askfor block 219dd1f224a675746881   1445726140000000
askfor block 8abaf81373a5a891236d   1445726140000000

**Comment by RdeWilde** [comment]
On Google mamy different cause are mentioned. One being about the clock, creating it's own fork.

Here the same error appeared too, but seems like it had a very specific cause https://bitbucket.org/JordanLeePeershares/nubit/issues/71/new-client-instances-unable-to-complete

**Comment by RdeWilde** [comment]
https://discuss.nubits.com/t/nud-freezes-when-booting-up/2588/33

**Comment by RdeWilde** [comment]
Fyi, killed the nodes

**Comment by Nerulls** [comment]
getting the same thing at the same block from a clean install

**Comment by mitchellcash** [comment]
The bitbucket link is identical to the issues I'm experiencing. I also confirm that if I restart the client it usually does push past the stuck block but will then get stuck again later on, rinse and repeat.

**Comment by RdeWilde** [comment]
https://github.com/Peershares/Peershares/pull/110

**Comment by RdeWilde** [comment]
Restarting or rebooting did not help for me though. Tried many times 10+. Might be irrelevant, just saying :-)

**Comment by mitchellcash** [comment]
Thanks for providing that Peershares link @RdeWilde. 

@IngCr3at1on when you have free time could you please take a look at this one.

**Comment by ligerzero459** [comment]
@RdeWilde might have given the perfect fix. Using that code from PeerShares I was just able to sync a new chain completely without restarting the daemon. 

I'll do a little more testing with @IngCr3at1on and submit a PR if it works consistantly

**Comment by mitchellcash** [comment]
@ligerzero459 thanks, I thought it looked like the perfect fix but I've been on holidays so no time to test :) I just landed back home now so if you need me to I can submit the PR

**Comment by ligerzero459** [comment]
I've already got the code written at this point. I'll open it up in a little bit :grin:

**Comment by mitchellcash** [comment]
Thanks!

**Comment by IngCr3at1on** [comment]
#337 should resolve this, closing issue.

**Comment by jacobworsoe** [comment]
When will this fix be released? Is there a beta we can use until then?

**Comment by mitchellcash** [comment]
@jacobworsoe the release is out right now. Please see https://github.com/PaycoinFoundation/paycoin/releases/tag/v0.3.3.0

**Comment by jacobworsoe** [comment]
Upgraded to 0.3.3.0 - still stuck on block 328798 :(

**Comment by HyperCommNet** [comment]
@jacobworsoe Please delete your current blockchain
# linux
    ~/paycoind stop
    cd ~/.paycoin
    rm -fr database/
    rm blk*.dat
    ~/paycoind
# windows
    Shutdown paycoin
    open File Explorer
    In Directory Bar Enter %AppData%\Paycoin
    Delete blk0001.dat & blkindex.dat also database folder
    Start paycoin back up.

**Comment by jacobworsoe** [comment]
@HyperCommNet Thanks it worked!

**Comment by tofutim** [comment]
why does this actually happen? it seems to be os selective

**Comment by ligerzero459** [comment]
@tofutim It happens now because Paycoin is defunct. There are no Prime controllers moving the chain and probably only a few nodes online that people have forgotten about

**Comment by IngCr3at1on** [comment]
well that's why the chain doesn't move today but that's not the reason the syncing was stalling when it was active.

@tofutim the PR that @ligerzero459 originally submitted to fix this actual issue resolved this particular issue (it was not OS specific); basically the old peercoin logic worked for peercoin because it was using PoW and PoS and it was using the PoW blocks as the reference block for download, however Paycoin was PoS only after the initial launch so there was no valid reference block; causing confusion when requesting the next block.

The original Peershares PR explains it pretty well: https://github.com/Peershares/Peershares/pull/110
