### ISSUE TITLE
Missing coin (follow up on #266)

### ISSUE THREAD

**Issue by allegro16** [PaycoinFoundation/paycoin#296]
Installed 0.3.2.0 in time before the fork, setup all my Micro Primes (3x 1000, based on 1x 100 Primes and 2x 10 Primes), sent coin to primes.. There all went wrong as the wallet crashed, some transactions orphaned and some confirmed. But not all correctly ended up in the wallet. I was particularly having issues with my 100 ZC Primes based Micro Prime.. It acted like a black hole.. I setup to send 1000XPY (as that's the limit) to it, but somehow the wallet decided to send 2000 or so on it's own.. The wallet balance is off now, as it doesn't correspond to the coins ACTUALLY in the Ledger..
According to the Ledger and the Paycoin.com support it seems that i indeed lost up to 2000XPY due to wallet issues in combination with transactions happened during blockchain issues/wallet being out of sync (while it said it was synced 100% of the time)

They asked if i could contact you to help out getting my coin back or reimburse.

I have all details but i won't post them here directly for safety.

Andre

---

Paycoin.com Support via reamaze.com 
05:43 (6 uur geleden)

aan mij 
 Richard	
Richard
Hi Andre,

Thanks for the additional information. We would rather not be in possession of your .dat or keys. Please do not send that to us. Also, Colin is correct in that the ledger (in normal cases) is the point of reference for the blockchain. However, since the fork issue, getting it resynced to the right data has been a challenge and as you can see it's still showing some strange/inaccurate data.

I apologize but at this point I'm not too sure we're going to be able to recover your coins. We've exhausted all of our typical troubleshooting steps. And since you've already set up a new .dat and imported your keys to it, that isn't looking like a solution either. Unfortunately it looks like all of those transactions took place during some kind of issue with the blockchain and your wallet being out of sync.

My only suggestion at this point is to open an issue directly with the coin developers on the github: https://github.com/PaycoinFoundation/paycoin/issues

They may have a solution that I'm not aware of, but it looks like we've exhausted the options we have available.

Regards,

-Richard

**Comment by RdeWilde** [comment]
Not really possible to figure out anything without source wallet address and txid.

**Comment by allegro16** [comment]
Hi, 

I replied to the email with details. If you haven't received, please send a direct email address to send everything to.

Did all that, as i was advised by support and users on Paycointalk. I confirmed i'm on the correct chain and did a listaccounts. The value doesn't correspond with the blockchain. I tried everything support suggested.
They confirmed my issue but have no idea how to resolve. I just want my coin back..

Andre

**Comment by RdeWilde** [comment]
I'm not the one to receive those mails, I'm just another user ;-)

So listaccounts lists the wrong account too? That's strange. But without the public details (which is fine) nothing I can look up. GL!

**Comment by allegro16** [comment]
LIst account gives wrong stats as well, or i don't understand them..

"" : -30081.70366000,
"Micro Prime 1" : 3000.00000000,
"Micro Prime 2 (Azk)" : 1999.99800000,
"Micro Prime 3 (CG)" : 1000.00000000,
"Regular wallet 1" : 0.00000000,
"Regular wallet 2" : 2937.60421200,
"Regular wallet 3" : 16973.98956500,
"Regular wallet 4" : 6173.49368200,
"Regular wallet 5" : 999.99900000
}

I also have a P93mjH1u89SXCoiKt1Vjk4pAEvTBnwLe4d "Regular wallet 6", but i think this backup doesn't list that. I only created that AFTER the troubles began..

This is the convo with support:

http://support.paycoin.com/conversations/downloaded-the-official-paycoin-blockchain-dot-imported-addresses-dot-checked-if-on-correct-chain-used-connect-equals-as-without-i-ended-up-on-the-fork-ans-still-i-lost-1000xpy-dot/perma?token=417710a228547#mid4135684

**Comment by RdeWilde** [comment]
Regular wallet 1 does not exists on the current chain: PMjmAuCQ3sAaxgTDzDy3V1Xe7Dx35WNvJu
Did you ever use it?

Others do list the received amounts right according the ledger.

**Comment by allegro16** [comment]
No, i don't think i did but support asked to list all addresses in the wallet or that i used.

Well, the ledger was OK, it seems, or at least partly.. But i'm still out 1000 or 2000XPY the ledger said was there and should be in my wallet.. But the're not..
https://ledger.paycoin.com/ i'm talking about, but it looks like they are reloading data as none is listed. That SAID 3000XPY in the wallet address that says 1000..
If the ledger at Chainz is more correct than the official, it still doesn't explain where the missing coins went..

**Comment by RdeWilde** [comment]
Can you eleborate on where the coins went missing? Or is this unknown? Date, transaction, wallet...

As said, the ledger lists all received + send so it can't have happened on this chain (or we are missing a wallet address).

Can you clear this up? "But i'm still out 1000 or 2000XPY the ledger said was there and should be in my wallet." Do you mean it should be there because the wallet said so? Or do you mean it should be there because you bought them?

Maybe you can track where you bought them and check the txid, maybe one was send on the wrong chain so you could identify it now as it would not be in the ledger anymore. The you can contact support for that (probably) exchange?

**Comment by allegro16** [comment]
It should be there as i had accumulated this and it WAS listed on the official ledger, but not in the wallet. Both me and support have no idea where the coins are/went, but not in any of my wallets according to the QT. The official Ledger still listed them though. I will see what's what when that ledger is back online.

It's a bit unknown indeed. Sometime last week. It was at least 1000XPY, according to support and the ledger up to 2000XPY even.

I listed all addresses i own, or it was sent due to a bug to an account i don't own?

It basically comes to this: before the 0.3.2.0 walletupgrade i had a certain amount of coins, after, when i sent it to the Micro Primes the wallet crashed and they were gone but DID show on the Ledger.

**Comment by allegro16** [comment]
Well, at least now Chainz is incorrect too!
I've setup scrape addresses, didn't move anything from the MP's under 1000XPY (i only took out the excess.. And now those MP's show as a 0.0 balance..

https://chainz.cryptoid.info/xpy/address.dws?PEUzsV9r4CtDoH6EiMHqvmR7Nb56CMruEi.htm
https://chainz.cryptoid.info/xpy/address.dws?PPMHJgXf74bSKrWkssp5yd44T7cmGyvGbG.htm

Scrape:
https://chainz.cryptoid.info/xpy/address.dws?P9fAPJWFaMLW5Gt8qFMXjVyDdxStJw97Bj.htm
https://chainz.cryptoid.info/xpy/address.dws?P9L1jzgkhF1ci4ZPqAf6cJHPCh4XjDFga1.htm

Where do all those coins end up? 

Also, i'm back having the block 345000 issue, while it ran OK for a day following the dev's advice to reinstall everything and download the blockchain without paycoin.conf..

**Comment by IngCr3at1on** [comment]
Chainz isn't incorrect, by not specifying the proper change address as your microprime the coins went to a new address in your wallet. This is default/standard behavior for all cryptocurrency. Without reviewing the complete issue (working on figuring out some of the overall chain and wallet issues at the moment) I wouldn't be surprised if this is part of your overall confusion.

https://en.bitcoin.it/wiki/Change

**Comment by allegro16** [comment]
But i DID set a scraping address: i created a new address for all 3 Micro Primes.
Micro Prime 1 Scrape 1, etc. Then set that address to the Micro Prime by clicking that corresponding field and put the address of the Scrape in.. Isn't that the way?

Or do you mean something else? Before 0.3.1.0 this worked for months.. Stakes ended up in the correct wallet. The only thing different here is that stakes would now end up in the Scrapes address, right? The MP's should still hold the rest? I thought this is how it's designed?

Anyway.. If it would be sent to a new address in my wallet: why doesn't it appear in the address list? 
And how can get it to behave like it's supposed to? I will update a screenshot, etc in an hour or so. Now busy updating all wallet backups to the new Scrape addresses.

**Comment by IngCr3at1on** [comment]
Change addresses are not scrape addresses, please read the link I pasted as it answers your other questions.

**Comment by allegro16** [comment]
Not really, no. As before 0.3.2.0 it didn't behave like this: if i've sent 500XPY of my 1000XPY balance from wallet 1 to wallet 2, 500 was sent and 500 stayed put. It didn't end up in a change address of sorts. At least, i think it didn't as before i could still see the correct amount on the ledgers..

But can i make the change address as the Micro Prime? As that's what i want/need as i already lost access to at least 1000XPY (that has nothing to do with this issue, even support is baffled), this get's way to difficult to track this way..

You say when i do a transaction i need to set a proper change address instead.. How? As in the GUI there is no way..

**Comment by allegro16** [comment]
I might get it now, it's badly translated in the Dutch wallet. But still:

It has NOTHING to do with the 1000/2000 lost coins.. As confirmed with Paycoin.com support.

**Comment by IngCr3at1on** [comment]
It wouldn't surprise me if the translations were off, I know almost no Dutch so I can't imagine I will be correcting that myself but if you'd like to contribute to translations yourself please feel free.

In regards to the missing coins I'm holding off on commenting until the ledger issues are sorted.

**Comment by dbroyhill** [comment]
Enable coin control features in Display Preferences. Now when you send coins you can choose a custom change address. It is necessary to specify this every time when sending the full balance of an address, otherwise it will end up on a change address. The Wallet GUI hides these addresses somewhat, although you can export the keys. Think of it like real life change when you give a 20 to pay for something that costs 10.

**Comment by allegro16** [comment]
Yeah, i got that by reading the link. But as it's an incorrect translation i thought it was used to setup where to return coins to in case of errors or like when you play in a ponzi (which i sometimes did) to make sure returns will go to the correct address.
It's called "teruggaveadres" in the QT. This use of "change" is called "wisselgeld" in Dutch. 
The correct translation should be "wisselgeldadres" (Direct word for word translation: "changemoneyaddress".

Anyhow, i think indeed we all have to wait for the blockchains (both Ledger, Chainz, etc) to resume normal operation before i can be sure money is really lost.

As i just updated several intermediary backups with all addresses i use. All had another value as balance. Even after a few hours, balance does not update to what it should be. 
(For instance, without the lost coin it should be around 3000XPY.. One has it as 1001.x, the other as 2001.x..

Hopefully the buggy wallet and blockchain issues of the last 3 weeks will be resolved soon, as this all hurts the coin..

**Comment by RdeWilde** [comment]
@allegro16 hit me up at  slack, I'm Dutch too, maybe we can figure out some more details.

**Comment by allegro16** [comment]
Well, still not have all my coins. But i was able to transfer all coin from the change addresses to my Micro Primes. The weird thing is: in coin control it didn't list the change address.. So, i looked it up in the ledger and then temporary (made backup) installed that address and when visible transferred the coin back to the MP. There should be an easier way though.. Anyway, it works. I'll still hope to see my XPY back but at least i didn't lose more..

**Comment by IngCr3at1on** [comment]
The change addresses are listed in inputs in coin control under the address the change was directed from (in other words if you hit the plus next to the microprime address the change address should have been there). It's still semi-confusing I understand but at the moment I'm not really sure of a better way to handle it and that is the standard method for all cryptocurrency so far as I know.

**Comment by RdeWilde** [comment]
As said before it is a lot of stuff to look up due the fork, so you'd be very helpfull to just track down where you got the coins and post the txid, where the sum of these would add up to the balance you say you should have (minus the stake). Only that way we could figure out where coins went missing, if any. 

Is it not that you are confused because of the ledger showing you more coins than you actually had, and because of that you are now thinking you are missing coins, while actually the ledger was just been corrent to show the right amount now?

**Comment by allegro16** [comment]
Hi,

That SHOULD be the way, yes.. But there was no plus or anything. It looked like it was already in the MP wallet, but it was not. After putting the wallet backup back and letting it update both the ledger and the wallet are OK and list it in the correct wallet.

And no, it showed more, yes. 3000, while it should be 2000. I'm sure i get it back though, now tracing all payouts over the last few days.

**Comment by mitchellcash** [comment]
If you want to help with translations https://www.transifex.com/paycoin/paycoin/ :)

**Comment by IngCr3at1on** [comment]
Old issue related to fork, closing.
