### ISSUE TITLE
Wallet 3.2.0 crash when sending transaction (Ubuntu)

### ISSUE THREAD

**Issue by RdeWilde** [PaycoinFoundation/paycoin#297]
Don't have much information to it, but I was creating a 800+ xpy transaction with manual selected input, and when I confirmed I wanted to send it *poof* wallet closed.

All I have is this:
Txid: 
a7ea17a3dc97644124c92b4c6535d7e345e27ed5ebe591f75cfc594d87d8577b

Debug.log:
Paycoin version v0.3.2.0 (2015-10-22 20:09:33 -0400)
Using OpenSSL version OpenSSL 1.0.1h 5 Jun 2014
....
CommitTransaction:
CTransaction(hash=a7ea17a3dc, nTime=1445891642, ver=1, vin.size=6, vout.size=1, nLockTime=0)
    CTxIn(COutPoint(6b699ff345, 1), scriptSig=304502210090753e8c7002a8)
    CTxIn(COutPoint(fee1c55f21, 1), scriptSig=30450220694b3588773ba707)
    CTxIn(COutPoint(296ba65f03, 1), scriptSig=3046022100ee8ab0e900e719)
    CTxIn(COutPoint(296ba65f03, 2), scriptSig=3046022100cc11b7447a9562)
    CTxIn(COutPoint(f807b9e995, 1), scriptSig=304502210098670f8935988a)
    CTxIn(COutPoint(f807b9e995, 2), scriptSig=3045022100f5a7d82c0623b4)
    CTxOut(nValue=629.007427, scriptPubKey=OP_DUP OP_HASH160 e134f2e50d0a339d1964a5eb742a7d1d6c8ab72a OP_EQUALVERIFY OP_CHECKSIG)
AddToWallet a7ea17a3dc  new
....
addUnchecked(): size 0
CTxMemPool::accept() : accepted a7ea17a3dc
Relaying wtx a7ea17a3dc

**Comment by IngCr3at1on** [comment]
Out of curiosity do you remember what the number of inputs was (weird question I know)?

**Comment by RdeWilde** [comment]
vin.size=6

6 :-)

**Comment by IngCr3at1on** [comment]
Oops, missed that in the log...
