### ISSUE TITLE
Windows client does not have tray icon

### ISSUE THREAD

**Issue by ssa3512** [PaycoinFoundation/paycoin#3]
The Paycoin client does not have a tray icon when minimized to tray - It just shows as a white area. ![image](https://cloud.githubusercontent.com/assets/1991399/5441832/fc2bf6a6-8461-11e4-9737-eee296cd78bf.png)

**Comment by IngCr3at1on** [comment]
Can anyone confirm this is fixed so it can be closed?

**Comment by HyperCommNet** [comment]
I can confirm this is fixed.
