### ISSUE TITLE
display projected combined even while staking in overview tab

### ISSUE THREAD

**Issue by mdpfeiffer** [PaycoinFoundation/paycoin#309]
Overview tab shows balance, actively staking balance, and unconfirmed balance. Since it takes 120 confirmations for staking balance, users should still be able to see the combined account balance (projected balance post-confirmation of staking).

**Comment by IngCr3at1on** [comment]
What you don't like having to add the two together? :P

**Comment by IngCr3at1on** [comment]
Closing because #464 has been merged.
