### ISSUE TITLE
Wallet / MicroPrime / Balance Issues

### ISSUE THREAD

**Issue by ParkaMark** [PaycoinFoundation/paycoin#317]
I have opened a support request with Paycoin support but they were unable to help me with this issue. I have a very broken wallet, and no matter what I do (having re-synced the blockchain several times, and manually re-importing private keys/wallet addresses back into a fresh wallet, verifying I am indeed on the correct chain, etc, etc), nothing fixes this problem.

The current state of my wallet is below:

    [
        {
            "account" : "",
            "address" : "PMDrMm27Uvqfzyy3HGfcgfAj7DzT624aUt"
        },
        {
            "account" : "MicroPrime",
            "address" : "PHhFMMNGCDCzoFnSBw4do9MHsV2LKQgGdi"
        },
        {
            "account" : "ZenCloud",
            "address" : "PBigtiBQ8J3CGo1VpagvTXy8ja2B8J3sAa"
        }
    ]

Here are the reported balances for each of these accounts:

    $ paycoind getbalance ZenCloud
    88.96441700

The above is wrong (check the ledger, I moved this to the MicroPrime address).

    $ paycoind getbalance MicroPrime
    88.96441700

    $ paycoind getbalance ""
    -88.10330600

There is also a single stake transaction which appears, no matter what I do, to be mapped incorrectly to the wrong address/account. It appeared just before the blockchain fork on or around the 23rd of October. This is also in the ledger/blockchain:

    {
        "account" : "",
        "category" : "stake",
        "amount" : 0.80111100,
        "confirmations" : 4089,
        "blockhash" : "0e3adf59c7c545c2168dbb9f1bd1e9e84591c63f3fbd73030f902226a0444b15",
        "blockindex" : 1,
        "txid" : "cbfa6cb4eee76ba21407750c6ee3eda516df35167c1caa1e227f6caea7f7bc8b",
        "time" : 1445933989
    }

Let me explain when I suspect this problem started.

I have always not used labels on my addresses, because I have not needed to. However, when I got my MicroPrime address, I wanted to split these (MicroPrime, ZenCloud payout address etc) into different labels (obviously, makes sense, right?).

At this point, and after already re-loading my wallet keys, I had 3 addresses in the wallet, all with the same empty ("") account label - MicroPrime address, ZenCloud payout address and another address which gets created automatically upon new wallet creation.

I then saw no way to rename labels against addresses, so I did the next best thing I could (thinking I was being smart) - re-imported the addresses (private keys) back into my wallet (whilst they already existed in the wallet!) but this time specifying a label ("ZenCloud", "MicroPrime" etc). This worked - it renamed the labels against each address - but I also got an error notification saying it hadn't worked properly. It was at this point, I got a "stake" transaction, as recorded here (and documented above):

https://ledger.paycoin.com/transaction/cbfa6cb4eee76ba21407750c6ee3eda516df35167c1caa1e227f6caea7f7bc8b

but the wallet appeared to assign it to label "" (a non-existent account) and that is when things went totally broken.

Wallet does not stake, and hasn't staked since this occurred. The entire thing is a mess. Multiple blockchain re-syncs and wallet key imports done using 0.3.2.0, no change. The above stake transaction appears to be the culprit.

If you need any further information, let me know, and I will try and reply as soon as I can.

Thanks.

**Comment by IngCr3at1on** [comment]
The account system has always been weird and that's why `listaccounts` is disabled in bitcoin by default because you do wind up with negative values when using it. You might try `listaddressgroupings` for more accurate balances.

Either way I'd recommend running `repairwallet`

**Comment by ParkaMark** [comment]
Already ran repairwallet, several times - no change.

So this is expected behaviour then? listaddressgroupings gives:

    [
        [
            [
                "PHhFMMNGCDCzoFnSBw4do9MHsV2LKQgGdi",
                89.06092800,
                "MicroPrime"
            ]
        ],
        [
            [
                "PBigtiBQ8J3CGo1VpagvTXy8ja2B8J3sAa",
                0.76460000,
                "ZenCloud"
            ]
        ]
    ]

I note these values do match the ledger. So I presume everything is actually OK then? Also, I note there is a stake on the MicroPrime address for the 27th so it seems it actually is staking (I've not setup a scrape address since I'm no where near the 1000 XPY limit for that).

**Comment by IngCr3at1on** [comment]
@ParkaMark those balances look right to me yes and yes as you noted the microprime address staked properly.

As for the stake on the ZC address those coins where on that address when they staked as far as the blockchain is concerned so there's no way of "remapping" that stake.

**Comment by ParkaMark** [comment]
That explains everything I need to know. Many thanks @IngCr3at1on .
