### ISSUE TITLE
Wallet wont go past block 336422

### ISSUE THREAD

**Issue by PaycoinMaster** [PaycoinFoundation/paycoin#320]
Wallet wont go past block 336422 when trying to sync fresh. This has happened on 5 wallets so far. What could be the issue?

**Comment by RdeWilde** [comment]
https://github.com/PaycoinFoundation/paycoin/issues/294 ?

**Comment by mitchellcash** [comment]
Potentially could be related but I do think we should leave this one as a separate problem even though it could be the same cause. Let's get @ligerzero459 to get his PR in for testing soon :)

**Comment by ligerzero459** [comment]
It sounds unrelated to my PR.  It sounds like the wallet ended up on the fork. @PaycoinMaster, take the hash from your highest block and check if it exists on Ledger

**Comment by IngCr3at1on** [comment]
This should be resolved with #338 I believe.

**Comment by IngCr3at1on** [comment]
I confirmed with @RdeWilde that he was able to sync from a fresh build off master so I'm closing t his issue.
