### ISSUE TITLE
feature: double-click on sync status fetches latest blockhash from ledger and compares

### ISSUE THREAD

**Issue by mdpfeiffer** [PaycoinFoundation/paycoin#325]
Feature Request:

Add a double-click activated function to the green check box in the status bar at the bottom:

The function queries the ledger for the block hash for the latest block and compares to blockhash for the same block on chain wallet is running.

Since the wallet and ledger may be out of sync, there would have to be a way to select the lower block height of the two sources being compared.

A potential problem would be if the ledger ever got onto a wrong fork. There would need to be a way to avoid conveying the message that the wallet is on the wrong chain, when it may in fact be the right one.

**Comment by mdpfeiffer** [comment]
I had originally posted this in the wrong repo.  (oops!)

mitchellcash commented on it:
 
> I like the idea of being able to identify being on a wrong chain but I think there could be a better way to solve the problem (if there is a solution) than this. This has its own range of potential issues for example one reason could be if the ledger is on the wrong chain itself that an unknowing user could get the wrong idea. No one says the ledger is always right. Also what if the ledger is being DDOSed or just down for maintenance.
>
> Apart from verifying against ledger I don't know how else you could check you're on the right chain as once you move onto a wrong chain that's all you see.
> 
> Going back to the reason of the ledger being unavailable for whatever reason I don't like to put a single source of truth or a single point of failure in the wallet like a check against ledger. I think the best solution is to honestly have more nodes out there so that when a new user goes through IBD the chances of being on the correct chain are much higher.
> 
> Of course this has a cost to it etc. which is why we aren't seeing it happen in the volumes we would like.

> For me I kind of am against the idea of putting checks and links in the wallet to third party services. Of course if this is what the majority wants it can be investigated.

**Comment by mdpfeiffer** [comment]
Good points. 
Would it be possible instead to create an RPC command that combines the getblockcount with getblockhash? like getblocklatest?

**Comment by IngCr3at1on** [comment]
I have to agree with @mitchellcash on his points otherwise I don't understand the last question.

**Comment by mitchellcash** [comment]
I think he just means in the debug console something like:
```
>getblocklatest
391148
e54bbc22683dce78a091cf3fdeabf0deed6e60e97198fbbcabfaaa7ca7f752e8
```

I'm not entirely sure about this. As mentioned we already have `getblockcount` and `getblockhash` which are great at what they do :P no need to bring in something that just does the two combined.

**Comment by IngCr3at1on** [comment]
Closing for reasons discussed. This feature would be redundant at best.
