### ISSUE TITLE
Coins missing from wallet

### ISSUE THREAD

**Issue by rugrat2553** [PaycoinFoundation/paycoin#343]
I sent 990 coins to a microprime over 3 transactions.  Only 100 of those coins are showing in my wallet.  Paycoin support sent me here since there was nothing they could do.  The coins show in the blockchain but not in my wallet.  I have run the check and repair commands per Paycoin support and nothing changed.  Please see the attached images that show the addresses and transactions.

To check them without typing them:
PTzPbeyfWPrNVyXxzXKx2mbQGGh9bEBbMe   <-- main, non microprime address
PH6ecdG9jYJiUuAPiZVgzQ3SvH6yLfhY7y  <-- microprime with nothing in it
PFy3jUN8GxkCBcmTsdKNab63vofF4yDaHL  <-- microprime with 990+ coins that only show 100 in my wallet

Thank you,
Kevin Ivester
![chainz](https://cloud.githubusercontent.com/assets/15689088/10997579/32031de0-845c-11e5-8263-5309b3ef8be3.jpg)
![ledger paycoin](https://cloud.githubusercontent.com/assets/15689088/10997580/3204cdde-845c-11e5-90bf-f47d4568339e.jpg)
![minting](https://cloud.githubusercontent.com/assets/15689088/10997581/3205aaec-845c-11e5-8e02-2856a10ca2a0.jpg)
![my addresses](https://cloud.githubusercontent.com/assets/15689088/10997582/3208acf6-845c-11e5-8fb6-0c2238930ff4.jpg)
![prime 2](https://cloud.githubusercontent.com/assets/15689088/10997583/3209151a-845c-11e5-8648-d5bf0e4460d8.jpg)
![prime](https://cloud.githubusercontent.com/assets/15689088/10997584/3209462a-845c-11e5-8837-96260343c40f.jpg)

**Comment by ligerzero459** [comment]
@rugrat2553 Looking at ledger.paycoin.com, I see transactions that are not redeemed by your wallet, meaning you're either on the wrong wallet version or on a fork. What version is your wallet and what's your highest block?

**Comment by rugrat2553** [comment]
Currently on 0.3.2.0 and block is 362561 at the time of this writing.  So I may have been on the wrong chain when I sent the coins?

**Comment by ligerzero459** [comment]
You were definitely on the right chain when you sent the coins, since it actually appeared in ledger. I figured you'd diverged since then, but you're up to date...I'm going to do some investigating and try to figure out what could cause this.

**Comment by rugrat2553** [comment]
Any luck on finding the issue?

**Comment by ligerzero459** [comment]
After some discussion, @IngCr3at1on and I have a strong feeling that your wallet may be corrupted in some way. We're thinking there are two possible solutions: start the daemon with the `-rescan` flag to force the wallet to rescan the entire blockchain looking for transactions involving your wallet address and if that doesn't work, dump your private keys, delete your wallet.dat and then import the keys into a new wallet.dat

**Comment by IngCr3at1on** [comment]
Well to be fair @ligerzero459 I said to "move" the wallet.dat rather than delete it :P

**Comment by rugrat2553** [comment]
I have already exported and imported the keys on a fresh computer and the same happens. I will try the re-scan flag when I get back to the computer. And update later.

**Comment by rugrat2553** [comment]
Rescan worked.  Now showing all coins in the wallet.  Thank you.

**Comment by IngCr3at1on** [comment]
Awesome-sauce, thanks for letting us know.
