### ISSUE TITLE
Add support to Paycoin URI

### ISSUE THREAD

**Issue by cryptoapi** [PaycoinFoundation/paycoin#36]
Add support to Paycoin URI (similar as bitcoin uri).

Example: paycoin:P9mP9FKrXqL46Si58pHdhGKow88SUPy1V8?amount=1&label=payment

Paycoin URIs are formed with a Paycoin address and some optional parameters, such as amount and label. Users can configure their browsers to launch Paycoin client when they click a Paycoin URI on webpage.

**Comment by mitchellcash** [comment]
@IngCr3at1on is this not already possible? If not can we add this to a roadmap?

**Comment by mitchellcash** [comment]
Ahh my mistake, just tested this and it does not exist in Paycoin. Let's add it to a roadmap :)

**Comment by IngCr3at1on** [comment]
@mitchellcash fine with me, personally I don't have access to modify the existing roadmap or I probably would have done so sooner. @jwrb might be able to help with that in some way.

**Comment by IngCr3at1on** [comment]
I believe @mitchellcash has this mostly working if not fully, haven't seen the PR so I'm not sure.

**Comment by mitchellcash** [comment]
Only mostly working at this stage.

Linux build is working fine but Windows build is causing the issue at the moment and seeing as most users are probably on Windows I would like to get this working first. I just need to dedicate a bit of time on it and hopefully I can get it over the line in the near future :)

**Comment by IngCr3at1on** [comment]
Let me know if you need any assistance with debugging your issue.

**Comment by mitchellcash** [comment]
@cryptoapi sorry this took me ages. I hit a wall and forgot about it until recently. It's now submitted as a pull request here: https://github.com/PaycoinFoundation/paycoin/pull/282

If you want to test and comment on the pull request please do :)

**Comment by IngCr3at1on** [comment]
This was added w/ #282, closing issue.
