### ISSUE TITLE
MP transaction cause wallet to lose sync

### ISSUE THREAD

**Issue by TCB47** [PaycoinFoundation/paycoin#363]
I'm running wallet 3.3.0 and it now seems that every time I get a stake via the MP, the wallet quits syncing.  Running Win 7 Pro 64 bit with 64 bit wallet.
Last night, I removed all of the block chain, everything except wallet.dat by moving the old information to a temporary directory.  This morning when I checked, the wallet showed I had resynced but I had lost more than 2000 coins.  So, I dumped the new block chain, put all my old data back in place, let it sync up once again, and the coins had returned.
At 12:04 CT, I received a MP stake transaction, and since then the wallet lost sync and has been 7 blocks remaining ever since.  How can anyone trust this wallet???

**Comment by TCB47** [comment]
Update:  I wiped out the blockchain and everything else other than my wallet.dat file as the wallet reverted to not syncing on an MP stake, again, after reloading & syncing the wallet.  How do you expect this coin to succeed if you can't provide a working, stable wallet?  I've had to suspend plans to buy more XPY as the last time I tried this "fix" I lost 2K+ coins on the rebuild. I put the old blockchain back in place and my coins came back.

**Comment by ligerzero459** [comment]
Was this resolved when the fork occured, @IngCr3at1on?

**Comment by IngCr3at1on** [comment]
@ligerzero459 certainly should be yes, I haven't heard anything else about it

**Comment by TCB47** [comment]
Apparently, yes it has been resolved.
 
Tom Berwick
======================================
"The future ain't what it used to be."       ...Yogi Berra
 

  _____
