### ISSUE TITLE
Ubuntu wallet 3.3 crash

### ISSUE THREAD

**Issue by RdeWilde** [PaycoinFoundation/paycoin#377]
```
$ ./paycoin-qt -rescan
*** Error in `./paycoin-qt': munmap_chunk(): invalid pointer: 0x000000000ceee619 ***
Terminated (memorydump created)
```
(The last line I translated from Dutch)

Wallet showed up after splash screen (rescan). I was able to do a few clicks and then it just crashed and disappeared. I was fully synced. Ubuntu 15.04

Nothing spectacular in debug log
```
Your balance is 0 and reservebalance is 0
received block 42f8acb58730204d945c
SetBestChain: new best=42f8acb58730204d945c  height=380299  trust=210387788986693  moneysupply=16310311.472535
ProcessBlock: ACCEPTED
received block c60474b8d9bb130a1f56
SetBestChain: new best=c60474b8d9bb130a1f56  height=380300  trust=210387906452795  moneysupply=16310317.506746
ProcessBlock: ACCEPTED
received block e1429822c535d5fce739
SetBestChain: new best=e1429822c535d5fce739  height=380301  trust=210387975550504  moneysupply=16310317.678823
ProcessBlock: ACCEPTED
Your balance is 0 and reservebalance is 0
Added 551 addresses from 65.60.234.155: 16 tried, 9678 new
Added 545 addresses from 65.60.234.155: 16 tried, 9608 new
Added 276 addresses from 65.60.234.155: 16 tried, 9578 new
askfor block ca53768f611ad2aa2684   0
sending getdata: block ca53768f611ad2aa2684
received block ca53768f611ad2aa2684
connection timeout
SetBestChain: new best=ca53768f611ad2aa2684  height=380302  trust=210388107865295  moneysupply=16310318.192865
ProcessBlock: ACCEPTED
trying connection 80.99.1.187:8998 lastseen=7,8hrs
connected 80.99.1.187:8998
Your balance is 0 and reservebalance is 0
trying connection 74.216.26.53:8998 lastseen=15,1hrs
Your balance is 0 and reservebalance is 0
Your balance is 0 and reservebalance is 0
Added time data, samples 3, offset -2 (+0 minutes)
Moving 80.99.1.187:8998 to tried
version message: version 70006, blocks=380302
Your balance is 0 and reservebalance is 0
Your balance is 0 and reservebalance is 0
Your balance is 0 and reservebalance is 0
Your balance is 0 and reservebalance is 0
connection timeout
trying connection 213.148.167.242:8998 lastseen=7,5hrs
```

May be related to?
``` 
~/paycoin-master/src$ ./paycoind checkwallet
{
    "mismatched spent coins" : 9,
    "amount in question" : 5008.78528400
}
```

**Comment by IngCr3at1on** [comment]
Strictly speaking the most I can say with certainty based on that is that it's some form of memory error.

**Comment by jwrb** [comment]
I'll test this but I'm fairly certain it's a local memory issue and not one with the Paycoin software, as @IngCr3at1on stated already

**Comment by jwrb** [comment]
I would suggest running Memtest from your Bios (assuming you are using Grub) to check your machines memory if possible @RdeWilde.

**Comment by RdeWilde** [comment]
It's still crashing. Other application have no such problem. So I don't think it can possibly be bad memory.

**Comment by jwrb** [comment]
Could you provide us with more system information? A memory test would also be helpful as I mentioned above! I've fired up a VM to see if I can replicate this issue so we can get to work on fixing it!

**Comment by RdeWilde** [comment]
@jwrb If I am the only one experiencing this problem, I'd say this is a local issue/incident and we close this so IF anyone else is experiencing the same, we can re-open it :)

**Comment by jwrb** [comment]
That's what I'm trying to ascertain @RdeWilde. Hence why I asked for more information and a memory test on your behalf.

Are you able to reproduce this issue?

**Comment by RdeWilde** [comment]
Currently my wallet doesn't crash, though it does disappear. When I check the proceslist, it's still there, I just can't open the gui anywhere. I guess this is a seperate issue.

Not sure what you need?
Linux desktop-dewilde 4.2.0-19-generic #23-Ubuntu SMP Wed Nov 11 11:39:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I'll see if I have time somewhere soon to do the memtest stuff.

**Comment by jwrb** [comment]
I'll have a look. See if I can replicate the disappearing act you're experiencing at least.

**Comment by jwrb** [comment]
@RdeWilde Are you using the default WM? Unity (with the sidebar on the left)

**Comment by RdeWilde** [comment]
Yes

**Comment by jwrb** [comment]
great. What exactly happens when the wallet disappears? Are you doing anything specific? Do you notice any other issues?

**Comment by IngCr3at1on** [comment]
<sarcasm>That's a feature, it's called "Houdini UI"</sarcasm>

**Comment by RdeWilde** [comment]
@jwrb Just wallet is gone. Have to kill the proces thru cli and then start the wallet again.

I also sometimes have the issue that the top-bar menu is not showing while Paycoin-qt is active.

**Comment by jwrb** [comment]
I cannot seem to replicate this issue on 15.04 with the latest release of the wallet. Is there anything within your debug.log?

**Comment by RdeWilde** [comment]
@jwrb Nope, see first post.
