### ISSUE TITLE
Forked Blocks inside new synced empty wallet.

### ISSUE THREAD

**Issue by PaycoinDumbo** [PaycoinFoundation/paycoin#385]
I loaded/synced the walletchain now over 5 times (in different wallets) from Zero, even with empty Paycoin folder.....allways have wrong Blocks from 380237 - 380984 in my Chain which not matching with ledger!

"getblockhash" between 380237 and 380984 not matching ledger!

17:39:46 getblockhash 380240
17:39:46 d59a2fcec6e6b1420699eef17e9b009374656ea74c518f2e56dbb3fbe2a803be

17:40:40 getblockhash 380870
17:40:40 b2b3456812822d72d4fcac88e0f3166202d284898524b0064eff32248cab1e40

https://paycointalk.org/topic/1028/resolved-wrong-chain-again/52
https://paycointalk.org/topic/1028/resolved-wrong-chain-again/55

**Comment by IngCr3at1on** [comment]
They match up just fine so far as I can tell....

I just synced a wallet yesterday:
![selection_177](https://cloud.githubusercontent.com/assets/922158/11374826/a82eda6e-929d-11e5-839c-ec3ab6cb1d9c.png)

The first is the block height at the time of my looking now. As you can see all 3 hashes match on the ledger:
https://ledger.paycoin.com/block/805228a0902c464b3eff1adeb4e592083315a3e37612648e9100d9cc8c6fff43

https://ledger.paycoin.com/block/d59a2fcec6e6b1420699eef17e9b009374656ea74c518f2e56dbb3fbe2a803be

https://ledger.paycoin.com/block/b2b3456812822d72d4fcac88e0f3166202d284898524b0064eff32248cab1e40

**Comment by PaycoinDumbo** [comment]
Yes, now after ledger rebuild this "forked" Blocks match! 
But not before.
After this rebulid today I lost many of debits that was confirmed and matching with ledger before.
How can it be, that the "officiall" ledger was the incorrect chain?

**Comment by scroogemcdev** [comment]
Being that the ledger is managed by Team Paycoin rather than the development team (XPY Dev) I have no direct information on this. However since it's resolved I'm closing this issue.
