### ISSUE TITLE
translation_process.md needs updating

### ISSUE THREAD

**Issue by IngCr3at1on** [PaycoinFoundation/paycoin#396]

**Comment by mitchellcash** [comment]
What am I missing, in what way?

**Comment by IngCr3at1on** [comment]
Take a close look at translation_process.md (in particular the side for syncing translations)

**Comment by mitchellcash** [comment]
I'm lost haha. I still can't find what you're talking about

**Comment by IngCr3at1on** [comment]
Yeah I don't know maybe it was in the transifex PR and I didn't see it cause I just looked at the md file and it looks fine now... forget it lol
