### ISSUE TITLE
Invalid PrimeNode Key

### ISSUE THREAD

**Issue by mitchellcash** [PaycoinFoundation/paycoin#405]
On the testnet using the latest master to build it seems that it is no longer correctly initiliasing using a what is a correct PrimeNode key upon a clean launch.

To reproduce:
1. Clean out the testnet3 folder apart from wallet.dat
2. In paycoin.conf ensure you are using `testnet=1` and a correct `primenodekey`
3. Will throw an error `initPrimeNode() : invalid primenode key`

If you are working from a past build in which it did allow you to use a PrimeNode key then you won't experience this issue using the latest master for whatever reason. It is only when you clean out the data directory that it starts causing this error.

**Comment by mitchellcash** [comment]
Actually something in the master branch has destroyed the testnet flags. I don't even think the testnet is initialising at all hence the primenodekey not working because it's trying to validate it on mainnet.

**Comment by mitchellcash** [comment]
Okay I found the problem and the fix can be found in #406.

**Comment by IngCr3at1on** [comment]
@mitchellcash this was fixed with #386 right?

**Comment by mitchellcash** [comment]
It sure does
