### ISSUE TITLE
Windows 10 wallet crash

### ISSUE THREAD

**Issue by RdeWilde** [PaycoinFoundation/paycoin#408]
My wallet just crash when I clicked 'minting'.

I'm on Windows 10. Wallet had been running for about a day.

![Screenshot](http://i.imgur.com/OJExtq6.png)

Log isn't showing anything special.

```
askfor block c164dd30c8fd7c541356   1449672239000000
received block c164dd30c8fd7c541356
SetBestChain: new best=c164dd30c8fd7c541356  height=401258  trust=223028769207327  moneysupply=16439524.003292
ProcessBlock: ACCEPTED
Your balance is 1000000000 and reservebalance is 0
Your balance is 1000000000 and reservebalance is 0
Your balance is 1000000000 and reservebalance is 0
```

**Comment by ligerzero459** [comment]
I'm guessing this is related to a memory issue, as I get a similar crash if I send a transaction after the wallet has been open for a few days. My log also shows nothing special

**Comment by mitchellcash** [comment]
I'd say this relates to #176. And yes I think it's a memory issue as well as I experience both the minting tab crash and also the sending transaction crash.

@IngCr3at1on and I have put a few memory fixes in since the last release so we will see how that affects it all.

**Comment by IngCr3at1on** [comment]
Closing in favor of #457 as we will be debugging this there.
