### ISSUE TITLE
Cannot connect to testnet

### ISSUE THREAD

**Issue by mitchellcash** [PaycoinFoundation/paycoin#443]
My testnet wallet is failing to connect to the testnet. Is the DNS seed `tseed.paycoin.com` down maybe?

**Comment by mitchellcash** [comment]
Okay so this is only for new wallets trying to connect to the network. A wallet that has previously been on the network seems to be fine presumably because it is sourcing a list of peers from peers.dat rather than the DNS seed.

ping @HyperCommNet is this something you are able to get back online?

**Comment by RdeWilde** [comment]
Got same problem, obviously. Will try adding manually.

**Comment by IngCr3at1on** [comment]
I believe this is resolved.

**Comment by mitchellcash** [comment]
Looks good.

**Comment by ligerzero459** [comment]
I don't think this fixed, or the DNS seed is offline again. I can't sync a new testnet wallet

**Comment by mitchellcash** [comment]
Is is this testnet DNS seed connected in anyway to the testnet ledger, coincidentally also down...

@ligerzero459 here's some IPs to use in the meantime:
```
addnode=196.210.10.5
addnode=73.55.148.22
addnode=24.246.28.36
```

**Comment by IngCr3at1on** [comment]
Yes I believe the seed is connected to the ledger. It certainly was working when I connected a new node without a peers.dat file but I haven't checked in the last 24 hours.

**Comment by IngCr3at1on** [comment]
Basically we need a new DNS seed for the testnet.

**Comment by mitchellcash** [comment]
Who was running the one we had, are they leaving it offline?

I am happy to contribute one but I will need to look into how to create one... is BIND9 what is being used?

**Comment by IngCr3at1on** [comment]
@mitchellcash I believe yoshi was running the other and yes he's unable to restart it at this time. I'm not sure what you mean by BIND9 without googling it but there's really nothing complex about setting up a seednode.

The following is a copy of the xpydev mainnet seednode conf (with rpc info redacted), obviously a testnet node would also need testnet=1

```
daemon=1
dbcache=100
rpcuser=...
rpcpassword=...
maxconnections=25
```

Beyond that you'd need to decide the best way to start the node on bootup for your particular system/configuration (this obviously varies)

**Comment by mitchellcash** [comment]
This doesn't seem like a proper DNS seeder though right? In any event I'll set this up tomorrow using your configuration :)

**Comment by mitchellcash** [comment]
Okay I have a node running at `testnet-seed.paycoin.mitchellcash.com` using the above instructions.
