### ISSUE TITLE
(Testnet) Windows QT Wallet Crashed on Stake

### ISSUE THREAD

**Issue by CeForce** [PaycoinFoundation/paycoin#457]
Follow up to previous issue
After i restarted my wallet, the test prime staked and crashed the wallet as well. (windows 10, paycoin qt 3.3.1) The prime address did not have a scrape set (for what it's worth)

It looks like the stake was accepted and the previous tx that crashed the wallet confirmed at the same time. Debug log attached. Includes the prime stake and reopening the wallet after the crash. 

[debug2.txt](https://github.com/PaycoinFoundation/paycoin/files/93222/debug2.txt)

**Comment by IngCr3at1on** [comment]
So this is an otherwise silent crash (you don't get any form of popup from windows, etc stating it crashed)?

**Comment by CeForce** [comment]
I get the pop up that says Paycoin.exe has stopped responding. After acknowledging the the window the wallet and the message both do away.
