### ISSUE TITLE
2.0 release loses all coins because of fork.

### ISSUE THREAD

**Issue by RdeWilde** [PaycoinFoundation/paycoin#63]
Please hold back and rollback current changes until issue is resolved.

Using the 2.0 release of the wallet will bring you on another chain from April 20, so you can potentially lose all coins!

There should be a big WARNING at the very least! Otherwise people will get screwed.

**Comment by BoXHocK** [comment]
There is a simple fix to this issue; update the wallets. If everyone would do that already, this wouldn't have been an issue.

**Comment by IngCr3at1on** [comment]
There is a very clear warning in the release notes.

**Comment by IngCr3at1on** [comment]
@PaycoinMaster can we close this?
