### ISSUE TITLE
[MAC] Issues with building from source

### ISSUE THREAD

**Issue by whitj00** [PaycoinFoundation/paycoin#68]
Your paste is http://pastebin.aquilenet.fr/?42290d2fa0a1adb0#2TeE2u4hTjBZ3NnfFwkBkGTEKHxoyfFfk/ldESh19zo=

**Comment by mitchellcash** [comment]
Please close. Link has expired and no further description as to the issue.

**Comment by IngCr3at1on** [comment]
Yeah this is old I agree with @mitchellcash I'm closing this. It can be re-opened if an issue is discovered.
